language: csharp
solution: Bebop.Monads.sln
install:
  - nuget restore Bebop.Monads.sln
  - nuget install NUnit.Runners -Version 3.8.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release Bebop.Monads.sln
  - mono ./testrunner/NUnit.Console.3.8.0/tools/nunit-console.exe ./Tests.Bebop.Monads/bin/Release/Tests.*.dll
matrix:
  include:
    - mono: latest
